version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment: docs/doc_env.yml

python:
  install:
    # Install our python package before building the docs
    - method: pip
      path: .
